version: '3.3'

services:

  backend:

    build:

      context: .

      dockerfile: Dockerfile

    ports:

      - "127.0.0.1:3000:3000"
    environment:

      - DATABASE_URL=${DATABASE_URL}

    dns:

      - 8.8.8.8

      - 1.1.1.1

    env_file:

      - .env

    restart: always

  frontend:

    build:

      context: ./Monipro_web

      dockerfile: Dockerfile

    ports:

      - "127.0.0.1:8080:80"

    depends_on:

      - backend

    restart: always
