server {

    listen 80;

    server_name moni-pro.app.br www.moni-pro.app.br;



    location / {

        root /usr/share/nginx/html;

        index index.html index.htm;

        try_files $uri $uri/ /index.html;

    }



    # Se a sua API for chamada pelo mesmo domínio no futuro, podemos redirecionar aqui

    error_page 500 502 503 504 /50x.html;

    location = /50x.html {

        root /usr/share/nginx/html;

    }

}
